In [1]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline



In [2]:
# np.sum does column wise thing
# h = 1/(1+e^-XTheta)
# J = sum(-log(h)y-log(1-h)(1-y))/m
# delJ is checked to be sum(x*(h-y))/m

def sigmoid(z):  
    return  1/(1+np.exp(-z))
#     return np.array(map(float,list(map(lambda x:1/(1+(np.e)**(-x)) , z))))
def calcCost(m,h,y):
    J = np.sum(np.log(h)*y + np.log(1-h)*(1-y))/m*-1
    return J

def getGrad(m,X,h,y):
    delJ = np.matmul(X.T,h-y)
    return delJ

"""
Coding the NN - 
M1 - 
    code layer wise => There is one weight matrix between two layers. That has dimensions dim(l1)xdim(l2)
    The matrix is 
M2 -
    code unit wise => lot of units need to be coded into it. This is pointless.

"""


'\nCoding the NN - \nM1 - \n    code layer wise => There is one weight matrix between two layers. That has dimensions dim(l1)xdim(l2)\n    The matrix is \nM2 -\n    code unit wise => lot of units need to be coded into it. This is pointless.\n\n'

In [20]:
class Perceptron(object):
    def __init__(self,alpha=0.01,iters=50,weight=[-1]):
        self.alpha=alpha
        self.iters=iters
        self.weight=weight
    
    def train(self,x,y):
        X=x.copy()
        m,n=X.shape
        X =np.insert(X,0,1,axis=1) # insert the column of ones
        self.weight = np.random.randn(n+1,1)*0.1 #N+1 x 1
        for _ in range(self.iters):
            h = self.getH(X)
            self.weight= self.weight - (self.alpha/m) * getGrad(m,X,h,y)
        return self.weight
    
    def predict(self,X):
        h = self.getH(X)
        return np.array([1 if hi>=0.5 else 0 for hi in h])
    
    def getH(self,X):
        self.out = sigmoid(np.matmul(X,self.weight))
        return self.out
        

pp = Perceptron(iters=10000)
X= np.array([    [0,0],    [1,0],    [0,1],    [1,1],])
y = np.array([    0,    1,    1,    1,]).reshape((4,1))
pp.train(X,y)
print(pp.weight)

m,n=X.shape
X =np.insert(X,0,1,axis=1) # insert the column
X=np.random.permutation(X)
p=pp.predict(X)
print(p)
p = p.reshape((p.shape[0],1))
print(np.concatenate( (X,p),axis=1))

[[-1.46178415]
 [ 4.00205412]
 [ 4.0041971 ]]
[0 1 1 1]
[[1 0 0 0]
 [1 1 1 1]
 [1 0 1 1]
 [1 1 0 1]]
